samples/python/agents/crewai/README.md
samples/python/agents/langgraph/README.md

Improves documentation for LangGraph Currency and CrewAI Image Generation agents:
- **CrewAI Documentation**:
- Added sequence diagram and flow explanation
- Enhanced component descriptions and setup instructions
- **LangGraph Documentation**:
- Added sequence diagram showing interaction patterns
- Improved A2A protocol integration details
- Added streaming capabilities explanation

docs: Enhanced Documentation for LangGraph and CrewAI

---

topics/a2a_and_mcp.md

Remove extra word on a2a_and_mcp.md

---

README.md

This pull request fixes a minor grammatical issue in the Contributing section of the README.

fix: correct grammar and formatting in Contributing section

---

samples/python/agents/google_adk/agent.py

chore: update agent.py

---

topics/a2a_and_mcp.md

Just fixing 1 typo when reviewing the full page. See commit diff for details

Update a2a_and_mcp.md: fixing a typo

---

topics/agent_discovery.md

Hi, just fixing 2 typos on this page after reviewing it in full. See commit diff for details.
Didier

Update agent_discovery.md: fixing 2 typos

---

documentation.md

Fixing 2 typos in this file after reviewing it in details.
Didier

Update documentation.md: fixing diverse typos

---

demo/ui/components/form_render.py
demo/ui/state/state.py
samples/js/src/agents/coder/code-format.ts
samples/python/common/utils/push_notification_auth.py

This PR corrects some typos in the codebase

chore: correct some typos

---

README.md

Update README.md for Contributing section

Update README.md for Contributing section

---

demo/ui/service/server/adk_host_manager.py
demo/ui/service/types.py
samples/python/hosts/multiagent/remote_agent_connection.py

Provides the task callback with the agent card associated with the remote agent. Uses this information to record events into the event stream rendered in the demo UI

Add remote agent events to event stream

---

demo/ui/components/form_render.py

Use the value of the updated form instead of the original value of the element

fix: using the updated variable

---

samples/python/hosts/multiagent/host_agent.py

Hi,
Changed 'response' to 'respond' as verb is needed in the constuct.
See commit diff for details
Didier

Update host_agent.py: fix verb instead of noun

---

demo/ui/components/form_render.py

Hi,
'an' is not appropriate here: 'a' is the right form.

Update form_render.py: fixin 1 typo

---

demo/ui/components/async_poller.py

Hi,
Adding missing 'l' to invisible
DIdier

Update async_poller.py: fixing 1 typo

---

documentation.md

Doc changes to clarify push config

---

samples/python/hosts/cli/push_notification_listener.py

Hi,
Given the sentence 'is' is the right word and not 'in'
Best,
Didier

Update push_notification_listener.py: 'is' rather than 'in'

---

samples/python/agents/google_adk/agent.py

Hi,
Fixing typo: "who handle" -> "who handles"
See commit diff for details
Didier

Update agent.py: fixing 1 typo

---

samples/python/hosts/multiagent/host_agent.py

fix: correct grammatical errors in host agent's instruction

Fix grammatical errors in host_agent root_instruction

---

docs/community.md
docs/index.md
docs/partners.md
docs/resources.md
docs/specification/agent-card.md
docs/specification/agent-to-agent-communication.md
docs/specification/index.md
docs/specification/overview.md
docs/specification/sample-messages.md
docs/topics/a2a-and-mcp.md
docs/tutorials/python/2-setup.md
mkdocs.yml

Fixes https://github.com/google/A2A/issues/348.
This PR is for docs rework stage 2 of 3. See https://github.com/google/A2A/issues/347 for full context.
Screenshot at this point:

feat: Rework documentation, reorganize pages (Stage 2/3)

---

.github/workflows/docs.yml
docs/README.md

Fixes #349.
This PR is for docs rework stage 3 of 3. See #347 for full context.

feat: A2A docs rework; docs on docs; docs build and publish automation

---

docs/community.md

This PR makes an intention docs change to test CI/CD for docs and publish workflow.
See #347 for full context.

feat: Test docs updates

---

docs/community.md

This PR makes an intentional docs change to test CI/CD for docs and publish workflow.
See #347 for full context.

feat: Testing Docs CI publish and build workflow

---

docs/community.md

This PR reverts test docs changes that were used to test CI/CD for docs and publish workflow.
See #347 for full context.

feat: Revert test changes for docs CI/CD testing

---

samples/python/pyproject.toml

chore(samples/python): Lower `requires-python` to `>=3.11`

---

.github/actions/spelling/allow.txt
.github/actions/spelling/excludes.txt
.github/workflows/links.yaml
README.md
docs/documentation.md
docs/specification/agent-card.md
docs/specification/index.md
docs/specification/overview.md
docs/tutorials/python/4-agent-skills.md
docs/tutorials/python/5-add-agent-card.md
lychee.toml

- Add lychee checker for broken links
Fixes #384 🦕

docs: Fix Broken Links

---

docs/tutorials/python/9-ollama-agent.md

Fix typo  in 9-ollama-agent.md of python tutorial of docs dir

docs: Fix typo in 9-ollama-agent.md

---

samples/python/agents/crewai/README.md
samples/python/agents/crewai/__main__.py
samples/python/agents/crewai/agent.py
samples/python/common/client/client.py

It also fixes a timeout issue in sample A2A Client

fix: add VertexAI compatibility for CrewAI sample

---

.github/actions/spelling/allow.txt
samples/python/agents/README.md

In `samples/python/agents/README.md`, add missing sample agent descriptions for
* **AG2 MCP Agent with A2A Protocol**,
* **Marvin Contact Extractor Agent**,
* and **Semantic Kernel Agent**
---
Fixes #447 🦕

chore: Add missing agents in agents/README.md

---

README.md

Revert "docs:Update README.md"

---

docs/partners.md

feat: add MSFT to partners.md

---

specification/json/a2a.json
tests/test_a2a_spec.py

Addressing broken tests due to merge of incomplete PR

fix: Broken spec tests

---

demo/README.md

docs: fix google_adk bash cd

---

docs/community.md

docs: fix some incorrect content in the documentations

docs: fix some incorrect content in the documentation

---

samples/python/agents/google_adk/agent.py

fix: Broken adk agent tool functions

---

samples/python/README.md

Fixed minor sentence-break issue.

docs: Fixed minor sentence-break issue

---

samples/js/package-lock.json
samples/js/package.json
samples/js/src/agents/coder/genkit.ts
samples/js/src/agents/movie-agent/genkit.ts

chore: upgrade genkit to the latest version (1.8.0)

---

docs/partners.md

docs: Update partners.md

---

docs/specification.md

chore: Fix some markdown syntax errors

---

.github/workflows/docs.yml
docs/sdk/python/index.md
mkdocs.yml
requirements-docs.txt

Generate Documentation for Python SDK using mkdocstring

docs: Python SDK Initial Doc Gen

---

docs/sdk/python/index.md
mkdocs.yml

- Move SDK Reference before Tutorial in TOC
- Add `pip install` command to SDK Reference page

docs: Update SDK Reference page

---

demo/ui/service/server/adk_host_manager.py
demo/ui/state/host_agent_service.py
samples/python/hosts/multiagent/host_agent.py

- Address changes for ADK upgrade
- Fix bug with incorrect type -> kind replacement

fix(demo): Fix bugs in demo app

---

.github/workflows/generate-a2a-json.yml
specification/json/a2a.json
types/src/types.ts

Use @a2a-bot to auto-generate `specification/json/a2a.json` whenever `types/src/types.ts` is updated in a PR.

ci: Add Auto-generation of `a2a.json` from `types.ts`

---

specification/json/a2a.json
types/src/types.ts

chore: fix typo in types.ts doc comment

---

mkdocs.yml

docs: Update SDK Doc to show all enum values

---

.github/workflows/issue-metrics.yml

Add monthly issue with a report of issue metrics as described in: https://github.com/github/issue-metrics/tree/main

ci: Create issue-metrics.yml

---

.github/workflows/issue-metrics.yml

ci: Update issue-metrics to use actual repo name

---

docs/tutorials/python/2-setup.md

Updated docs to use requirements file added to the a2a-samples repo and updated path for the Start Server section.
Ref - https://github.com/google-a2a/a2a-samples/pull/67

docs: Python tutorial update

---

docs/tutorials/python/2-setup.md

This PR updates the Setup Your Environment documentation to correct the location of the requirements.txt file used for Python SDK installation. The file is located in the samples/python directory, and the updated command reflects this.
No code changes or functionality modifications were made—this is a documentation-only update for accuracy.
Fixes #698

docs: update Python tutorial instructions to correct requirements.txt path

---

GOVERNANCE.md

docs: Create GOVERNANCE.md

---

CONTRIBUTING.md

docs: Update Contributing Guide

---

specification/json/a2a.json
types/src/types.ts

- Prevents a breaking change in the Python Library

chore(spec): Add default value for `AgentCard.protocolVersion`

---

docs/topics/key-concepts.md

docs: fix a typo

---

docs/specification.md

A minor fix to the message/stream example to be valid JSON-RPC.

docs(specification): fix message/stream json-rpc example

---

.github/workflows/dispatch-a2a-update.yml

ci: Revert workflow update to use sha

---

.github/actions/spelling/allow.txt
.github/workflows/check-linked-issues
.github/workflows/check-linked-issues.yml

Make it mandatory to have an issue associated for spec changes going forward

ci: Enable linked issue checking for PRs

---

.github/actions/spelling/allow.txt
.github/workflows/conventional-commits.yml

Google GitHub App will be deprecated

ci: Add Conventional Commits Action

---

specification/grpc/a2a.proto

This is present in the JSON-RPC spec and was missing from the gRPC definition.
Fixes: #984

fix: Add name field to FilePart protobuf message

---

docs/partners.md

- [ x] Follow the [`CONTRIBUTING` Guide](https://github.com/a2aproject/A2A/blob/main/CONTRIBUTING.md).
- [ x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
Fixes #n/a

docs: Adding Infinitus to partner list

---

GOVERNANCE.md
specification/grpc/a2a.proto

docs: Governance formatting

---

GOVERNANCE.md

docs: Add GH for Sivakumar N. to GOVERNANCE.md
