- README.md
- Redirecting user to access demo video of A2A implementation.
- This PR solves #42 issue.
- The source link present inside the `<video>` tag return `The provided token has expired. Request signature expired at: 2025-04-09T17:49:15+00:00`.
```bash
<Error>
<Code>ExpiredToken</Code>
<Message>Invalid argument.</Message>
<Details>The provided token has expired. Request signature expired at: 2025-04-09T17:49:15+00:00</Details>
</Error>
```
> [Docs]: Add demo video link

- demo/ui/components/async_poller.js
- demo/ui/components/async_poller.py
- demo/ui/components/conversation.py
- demo/ui/components/header.py
- demo/ui/components/page_scaffold.py
- demo/ui/components/poller.py
- demo/ui/state/state.py
- Provide present intervals of 1, 5 and 30 seconds as well as a disable
- Show the user message immediately (no polling) regardless of setting
- Provide a force refresh, essential for disabled polling and long polling to get updated
> Add configurable polling to the UI

- documentation.md
- topics/enterprise_ready.md
Simple change that updates OpenAPI references to use the proper name.
> Replace all occurrences of "Open API" with "OpenAPI"

- samples/python/hosts/cli/README.md
The `uv run` command was written assuming user is in the `samples/python` directory.
And I was not able to run the `cli` host from outside the `python` directory with the command `uv run python/hosts/cli --agent [url]` because its not able to find the `common` module in the `python` directory.
by navigating to the correct directory in the first place `cd samples/python` I was able to run the cli host
> docs: Update README for CLI sample to correct directory navigation instructions

- demo/ui/pages/agent_list.py
I wasted some time, adding URLs of agents with `http://`in the add agents page, and I was not able to add a single running agent and it confused me, and was not sure, if the agents I started seperately can even be added, or if I need to add the `.well-known/agent.json` suffix.
With a placeholder its more clear to the User what is expected in the input box.
> Add a placeholder text for agent URL to make it clear to the user, what format is expected.

- demo/ui/components/chat_bubble.py
- demo/ui/components/dialog.py
- demo/ui/components/form_render.py
This PR fixes issue #108 where the dark mode in the web UI is not working correctly. Some UI components had hardcoded colors that didn't respect the theme settings.
Several UI components had hardcoded background colors like `#fff`, `whitesmoke`, `lightgreen`, and `smokewhite` instead of using theme variables. This caused these components to display with light colors even when dark mode was enabled, creating a poor user experience.
1. Updated `dialog.py` to use `me.theme_var("background")` instead of hardcoded `#fff` for dialog backgrounds
2. Updated `form_render.py` to use `me.theme_var("surface")` instead of hardcoded `whitesmoke` for form backgrounds
3. Updated `chat_bubble.py` to use theme variables for chat bubble backgrounds:
- Changed `lightgreen` and `lightgrey` to …
> fix: Update UI components to respect dark mode theme

- samples/python/agents/crewai/README.md
- samples/python/agents/crewai/__main__.py
Currently, there is a port inconsistency between the CLI client and the CrewAI agent service. The CrewAI agent was previously using port 10001, while the CLI client in samples/python/hosts/cli is configured to use port 10000. This inconsistency causes connection failures when trying to use the CLI client with the CrewAI agent.
~~Standardize the port usage across both components to use port 10000 consistently. This change ensures that the CLI client can connect to the CrewAI agent service without manual port configuration.~~
I've updated the documentation in `samples/python/agents/crewai/README.md` to explicitly specify the correct agent URL when running the CLI client
~~- Modified the CrewAI agent to use port 10000 by default (`as seen in samples/python/agents/crewai/__main__.py`)~~
~~- …
> Fix Crewai_CLI default connection

- demo/ui/state/host_agent_service.py
Noticed that event IDs were not being rendered in the demo app's event list.
This PR adds the event ID to the StateEvent constructor in convert_event_to_state() function by including `id=event.id`. This ensures the ID field is properly populated when events are displayed in the event viewer table.
> fix: missing ID field in StateEvent conversion

- samples/js/src/agents/README.md
**PR Type:** Documentation
This PR reorders the list of sample agents in the main `README.md` file to place them in alphabetical order:
1.  Coder Agent
2.  Movie Info Agent
> Fix agent path in README

- specification/json/a2a.json
This PR adds Message history to the Task schema definition so that the schema definition matches the technical documentation and example code.
The `tasks/get` input, `TaskQueryParams`, accepts `historyLength` as an integer parameter, which is documented to return the `last N items of history ... which will include all Messages, in order, sent by client and server`. Adding the History field to the Task definition makes this explicit.
[Task Definition](https://google.github.io/A2A/#/documentation?id=task)
```
interface Task {
id: string; // unique identifier for the task
sessionId: string; // client-generated id for the session holding the task.
status: TaskStatus; // current status of the task
history?: Message[];
artifacts?: Artifact[]; // collection of artifacts created by the agent. …
```
> Add history array to Task schema definition

- samples/js/src/client/README.md
- samples/js/src/schema.ts
When we're doing requests between TypeScript client and Python server there are some problem related to types:
```typescript
Part = TextPart | FilePart | DataPart 
```
in a client side contains an optional property type that doesn't go when doing request to a backend.
But on a Python server side there are a strict type validation
```python
Part = Annotated[Union[TextPart, FilePart, DataPart], Field(discriminator="type")]
```
That throws an exception when type is not provided 
```json
{
"jsonrpc": "2.0",
"error": {
"code": -32600,
"message": "Request payload validation error",
"data": [
{
"type": "union_tag_not_found",
"loc": [
"tasks/send",
"params",
"message",
"parts",
0
],
"msg": "Unable to extract tag using discriminator 'type'",
"input": {
"text": "hi"
},
"ctx": {
"discriminator": …
```
> Part (TextPart | FilePart | DataPart) type property should't be optional

- demo/ui/service/server/adk_host_manager.py
- demo/ui/tests/test_adk_host_manager.py
- Refactored ADKHostManager to reduce cognitive complexity in function response handling, the original function now has a uniform approach to appending data parts
- Code extracted to reduce complexity keeps original intact
- Removed a defect in FilePart instantiation where direct uri/mimeType assignment was not supported
- Added test suite in demo/ui/tests for ADKHostManager
- Added test cases for more coverage of the `adk_content_to_message` function
> refactor/fix: ADKHostManager Reduce cognitive complexity, test and fix defect

- samples/python/hosts/cli/pyproject.toml
- samples/python/hosts/multiagent/pyproject.toml
- samples/python/uv.lock
Adds "a2a-samples" as a dependency in `hosts/cli/pyproject.toml` and `hosts/multiagent/pyproject.toml`. Also, fixes `uv.lock` being out of sync (was missing some dev-dependencies).
Discovered this issue after running `uv sync` in a freshly cloned copy.
After the "splitting subproject-specific and common dependencies" change was applied (PR #182), I wanted to verify that environments worked as expected. So, I cloned the `main` branch into a new location (with no preexisting `.venv`'s) and after running `uv sync` noticed that `uv.lock` was out of sync and the "a2a-samples" dependency was missing in `hosts/cli` and `hosts/multiagent`. While the `multiagent` still worked from `demo/ui` because `demo/ui` directly requires "a2a-samples," the CLI client did not.
With this fix, the CLI client …
> Fix: Add missing "a2a-samples" dependency in hosts/*

- index.html
Uses the docsify built-in dark theme
Screenshots:
- system in dark mode:  
- system in light mode:
> Add dark mode (following system preference)

- samples/python/README.md
- samples/python/agents/crewai/README.md
- samples/python/agents/google_adk/README.md
- samples/python/agents/langgraph/README.md
- samples/python/agents/llama_index_file_chat/README.md
- samples/python/agents/semantickernel/README.md
Adding links to [uv](https://docs.astral.sh/uv/) official docs in
READMEs for those who do not have it installed.
> chore: link to uv docs in READMEs

- demo/ui/components/poller.py
There is already a property as shortcut for returning a single value.
```
@property
def value(self):
"""Shortcut for returning a single value."""
if not self.values:
return ""
return self.values[0]
```
> use e.value instead of e.values[0]

- README.md
For folks coming into this project, having a clarity on license off the bat is important. This PR adds a Apache 2.0 badge below the header image and clarifies a link to be Apache license.
> [Documentation] Clarify apache license in README.md

- specification/json/a2a.json
- tests/README.md
- tests/pyproject.toml
- tests/test_a2a_spec.py
- tests/uv.lock
This commit also makes running the A2A specification tests much simpler.
Fixes #264 🦕
> Remove 'null' support for JSON Schema types

- samples/python/agents/google_adk/agent.py
- samples/python/agents/google_adk/task_manager.py
This commit decouples the `TaskManager` in `samples/python/agents/google_adk` to be reusable by all Google ADK samples.
**Note:** This could potentially be refactored into a Google ADK specific `common` directory.
> Update the Task Manager in the Google ADK sample to be reusable

- samples/python/common/types.py
- specification/json/a2a.json
- tests/test_a2a_spec.py
This commit refactors authentication/authorization in A2A by modeling its support in the `AgentCard` _(and related API constructs)_ after OpenAPI. Here are the changes:
1. Remove `authentication` from `AgentCard` and replace it with a combination of `securitySchemes` _(analogous to OpenAPI's Security Scheme definitions)_ and `security` _(analogous to OpenAPI's Security Requirements definitions)_
2. Remove `authentication` from `PushNotificationConfig` and replaced it with `scheme` _(the Security Scheme that the push notification server uses)_ and `credentials` _(the same as `credentials` previously in `authentication`)_
3. Adds the appropriate types for describing _Security Schemes_ and _Security Requirements_
There is a follow-up PR coming that will demonstrate how to use this, and this …
> Update authn/authz to mirror OpenAPI Security Schemes/Requirements

- .github/workflows/links.yaml
As per tittle, protecting workflow checking links against failing runs on forks.
Hi,
Didier
- [X ] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [X ] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format)
> ci: protecting 'links' workflow against failing runs on forks

- docs/tutorials/python/2-setup.md
Made minor fix to pip command under step titled "Install the A2A SDK and its dependencies:"
Noticed that the command in step 2 - to install a2a and it's dependencies had a slight error. Fixed it.
> docs: tutorials/python/2-step.md fixed pip cmd

- samples/python/agents/headless_agent_auth/.env.example
- samples/python/agents/headless_agent_auth/README.md
- samples/python/agents/headless_agent_auth/__main__.py
- samples/python/agents/headless_agent_auth/agent.py
- samples/python/agents/headless_agent_auth/agent_executor.py
- samples/python/agents/headless_agent_auth/api.py
- samples/python/agents/headless_agent_auth/oauth2_middleware.py
- samples/python/agents/headless_agent_auth/pyproject.toml
- samples/python/agents/headless_agent_auth/test_client.py
- samples/python/agents/headless_agent_auth/uv.lock
This sample demonstrates how headless agent's tools can leverage [Auth0's Client-Initiated Backchannel Authentication (CIBA) flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-initiated-backchannel-authentication-flow) to request user authorization via push notification and obtain tokens for accessing separate APIs.
Additionally, it shows agent-level authorization via the [OAuth 2.0 Client Credentials flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow).
Allows an A2A client to interact with an external HR Agent, owned by Staff0, to verify whether the provided user data corresponds to an active Staff0 employee.  
With the user’s authorization (via push notification), the Staff0 HR Agent can access the …
> chore: auth0 sample (Auth for Headless Agents)

- specification/json/a2a.json
- types/src/types.ts
metadata was previously represented as metadata?: Record<string, any>, to imply this is a key-value pair. However defining in this format creates a new type in json-schema. To address the json schema generation, we used metadata?: object which fixes the generation issue. However, documenting metadata?: object in specification implies that metadata can accept more than just key-value pairs.
To address this, spec will still have metadata?: Record<string, any>, but we will use equivalent `{ [key: string]: any;}` to represent this attribute in types.
> fix: Replace metadata type with Record<string, any> equivalent

- .github/actions/spelling/expect.txt
- specification/json/a2a.json
- types/src/types.ts
Different fields are required/allowed for different OAuth flow types. Represent this by splitting flows into different types with the appropriate properties.
> fix: Split OAuth flows into different types

- docs/tutorials/python/2-setup.md
- docs/tutorials/python/3-agent-skills-and-card.md
- docs/tutorials/python/5-start-server.md
- requires Python 3.13
- AgentAuthentication has been removed from the SDK with the introduction of SecuritySchemes
> fix: Update tutorial with 0.2.0 changes

- specification/json/a2a.json
- types/src/types.ts
New boolean field 'supportsAuthenticatedExtendedCard' that if true, indicates an extended agent card is available at an authenticated endpoint.
> feat: Add a new boolean for supporting authenticated extended cards

- .github/workflows/dispatch-a2a-update.yml
- This allows triggering of the types.py generation in google/a2a-python
- Requirement for https://github.com/google/a2a-python/pull/92
> ci: Add dispatch-a2a-update Action for when a2a.json is updated

- .github/actions/spelling/allow.txt
- specification/json/a2a.json
- types/src/types.ts
Add missing JSDoc `@example` annotations to `AgentProvider` and `AgentExtension` interfaces to improve TypeScript developer experience.
Examples use Google ecosystem references (ai.google.dev, OAuth 2.0) and follow existing JSDoc patterns in the codebase.
First contribution to open source ❤️
> docs: Add `@TJS-examples` for `AgentProvider` and `AgentExtension` interfaces

- docs/topics/life-of-a-task.md
This pull request fixes a small typo in the Task state description. 🦕
An extra closing parenthesis was placed incorrectly:
Before:
...until it is in a interrupted state ()input-required or auth-required)...
After:
...until it is in an interrupted state (input-required or auth-required)...
This change improves clarity and corrects the formatting of the sentence.
> docs: improperly closed parenthesis in Task state description

- specification/json/a2a.json
- types/src/types.ts
Prevents usage of "Magic Strings" in SDKs, which supports better adherence to the recommended path for Agent Cards.
NOTE: This path might also need to be changed based on feedback in https://github.com/protocol-registries/well-known-uris/issues/66 so having a global constant would make this adjustment easier.
Fixes #816 🦕
> feat(spec): Add AGENT_CARD_WELL_KNOWN_URI to spec

- docs/specification.md
- added missing fields to the documentation
- added missing fields to example AgentCard in the spec
Fixes #842 🦕
> docs: Add Additional Interfaces and Preferred Transport to A2A Specification Documentation

- .github/workflows/sort-spelling-allowlist.yml
This PR adds explicit locale setting `LC_ALL=C` to the `sort` command used in the GitHub workflow, ensuring consistent behavior across different operating systems.
Fixes N/A 🦕
> chore: enforce consistent sort order in workflow using LC_ALL=C

- docs/specification.md
Changes the type reference in 7.7.1 from `ListTaskPushNotificationConfigRequest` to `ListTaskPushNotificationConfigParams`
Fixes #907
> docs: type reference in spec for `ListTaskPushNotificationConfigParams`

- specification/json/a2a.json
- types/src/types.ts
Adds Enum of supported Transports to Specification, with extensibility for proprietary protocols.
Adds URL formatting requirement for `AgentInterface.url` and `AgentCard.url`
Co-authored-by: Stefano Maestri <stefano.maestri@javalinux.it>
> fix(spec): Add Transport enum to specification

- types/src/types.ts
See https://github.com/a2aproject/a2a-python/pull/346
> fix(spec): Remove `@TJS-format uri` due to breaking change in Python SDK

- README.md
This PR adds a link to the .NET A2A SDK to the list of available A2A SDKs.
> docs: add a link to the .net a2a sdk to the list of available a2a sdks

- .github/CODEOWNERS
- GOVERNANCE.md
Make TSC CODEOWNERS for Spec and add missing GitHub accounts to GOVERNANCE
> chore: Update CODEOWNERS/GOVERNANCE with TSC

- docs/index.md
This PR adds .NET A2A SDK to the list of SDKs available to download.
> docs: add .net a2a sdk to the list of sdks available to download.

- docs/specification.md
- Fixes incorrect display of objects notated in #1092
> docs: Add header for 7.1.2 `MessageSendConfiguration` Object
